spring.application.name=order-service
server.port=8082

# ── PostgreSQL (own database — database-per-service) ──────────────────
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/order_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gila}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gila123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ── Product Service (inter-service REST call) ─────────────────────────
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}

management.endpoints.web.exposure.include=health,info
